### PR TITLE
CO-7491 CO-7499 : Parsing snapshot stat time issue while prune snapshots

### PR DESCRIPTION
**Pull request by Ramesh7**
- Fixing start time parsing for snapshot 
-  We intruduce stric UTC timezone parsing but AWS started managing respective region timezones which causing failure in parsing.
Below are commits where we intruduce explicit UTC parsing : 
https://github.com/coupa-ops/aws/commit/1a2106e2a06b23af4a5f4b22095a7d91a52bb5cf
https://github.com/coupa-ops/aws/commit/226f00fb59fd16a95e4d10a5d952609db1fb2a44

- [x] @sydneyrodrigues 
- [x] @faizsiddiqui 
- [x] @abriel 
- [ ] @autrejacoupa 
- [ ] @alokdnb 
- [ ] @coupacooke

### CODE REVIEW

**Comment by abriel** [comment]
API still returns time with "000Z" suffix.
Also, API version is versioned, so hard to believe that they changed something in a stable version.
Can you give some background please?
```
[spirit@eternal coupa]$ aws  ec2 describe-snapshots --filters Name=snapshot-id,Values=snap-052ddc6466d9d98a6 --profile coupa --region us-east-1
{
    "Snapshots": [
        {
            "Description": "Snapshot for db-storage-dev372db",
            "Encrypted": true,
            "KmsKeyId": "arn:aws:kms:us-east-1:899991151204:key/426a67a7-a97d-4cf4-affc-93470395a810",
            "OwnerId": "899991151204",
            "Progress": "100%",
            "SnapshotId": "snap-052ddc6466d9d98a6",
            "StartTime": "2018-11-29T11:51:26.000Z",
            "State": "completed",
            "VolumeId": "vol-0337d97f559e64f76",
            "VolumeSize": 1000,
            "Tags": [
                {
                    "Key": "timestamp",
                    "Value": "1543492286"
                },
                {
                    "Key": "device_count",
                    "Value": "4"
                },
                {
                    "Key": "lineage",
                    "Value": "dev372db"
                },
                {
                    "Key": "backup_uuid",
                    "Value": "i-0a384f0d0c72cd3cb-1543492282"
                },
                {
                    "Key": "device_number",
                    "Value": "3"
                }
            ]
        }
    ]
}
```

**Comment by Ramesh7** [comment]
Hi @abriel,
Recently observed that there are few failures and alert related to backup file age which is causing because of having different timezon in Oregon region. Here are few examples :
```
```

**Comment by abriel** [comment]
hm.. in the same region we have different suffix. I would say it is milliseconds and "Z" still means UTC.
Basically your fix makes sense, it just around to seconds. which is fine.
But there is a big difference in `strptime` and `strftime`.
with `strptime`, from the string "2018-11-29T01:38:38.813Z" we got time object matches to "2018-11-29 01:38:38". I am ok your changes here.
But with `strftime` we generate a string "2018-11-29T01:38:38.000Z" from a time object. and we need to leave to as is to match AWS format.

**Comment by Ramesh7** [comment]
@abriel our servers also runs on based on UTC and we are comming from comparing with UTC only. Also we are just comparing year month and day. So if there is minor diff in hours or seconds we will be good.

**Pull request merged**
